---
  # TODO: see about accessing from solr role (perhaps if both roles were called from same playbook?)
- name: restart solr
  service:
    name: solr
    state: restarted
  become: true

- name: restart apache
  service:
    name: "{{ apache_service }}"
    enabled: true
    state: restarted
  become: true
